apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-sistema-tasty-svc-product
spec:
  replicas: 2
  template:
    metadata:
      name: sistema-tasty-svc-product
      labels:
        app: sistema-tasty-svc-product
    spec:
        containers:
        - name: sistema-tasty-svc-product
          image: llaugustoll/tasty_delivery_svc_product:v1
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: configmap-tasty-sistema-tasty-svc-product
          resources:
            requests:
              cpu: 10m
  selector:
    matchLabels:
      app: sistema-tasty-svc-product