apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-postgres-product
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-hostpath-sc